In [1]:
from joblib import dump,load
import numpy as np
model=load('Dragon.joblib')

In [2]:
input=np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
        -0.24329153, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
        -0.97491834,  0.41164221, -0.86091034]])
model.predict(input)

array([22.286])

In [3]:
input2=np.array([[1,2,1,2,1,2,1,2,1,2,1,2,1]])
model.predict(input2)

array([21.686])

In [4]:
input3=np.array([[3,3,3,3,3,3,3,3,3,3,3,3,3]])
model.predict(input3)

array([19.725])